# config/packages/twig.yaml
twig:
    default_path: '%kernel.project_dir%/templates'
    globals: 
        app_public_url: '%app_public_url%'
    date:
        timezone: 'Europe/Paris'
    number_format:
        decimal_point: ','
        thousands_separator: ' '
    paths: []
    form_themes: []
    strict_variables: false
